#%RAML 1.0 DataType
properties:
  Name :
    type: string
    required : false      
  LastName :
    type: string
    required : false
  MobileNumber :
    type: number
    required : false
  UserName :
    type: string
    required : false
  Password  :
    type: string
    required : false
  Email :
    type: string
    required : false
  ShippingAddress   :
    type: string
    required : false
  ShippingCountry :
    type: string
    required : false
  ShippingPostalCode :
    type: number
    required : false
  ShippingStreet :
    type: string
    required : false
  ShippingState :
    type: string
    required : false
  BillingAddress :
    type: string
    required : false
  BillingState :
    type: string
    required : false
  BillingCountry :
    type: string
    required : false
  BillingPostalCode :
    type: number
    required : false 
  BillingStreet :
    type: string
    required : false 
  CreatedById :
    type: string
    required : false 
  CreatedDate :
    type: string
    required : false        
        