#%RAML 1.0 NamedExample
Data_example:
  value:
  -
    Name             : Ram
    LastName         : Asa
    MobileNumber     : 7013084527
    UserName         : MohanRamSai
    Password         : Ram@1234
    Email            : asamohanramsai@gmail.com
    ShippingAddress  : 37-177/1, Chilakaluripet,Purushothama Patnam
    ShippingCountry  : India
    ShippingPostalCode : 522616
    ShippingStreet   : Narasimharao Street
    ShippingState    : Andhra Pradesh
    BillingAddress   : 37-177/1, Chilakaluripet,Purushothama Patnam
    BillingState     : Andhra Pradesh
    BillingCountry   : India
    BillingPostalCode : 522616
    BillingStreet    : Narasimharao Street
    CreatedById      : 12345
    CreatedDate      : 17-03-2022
      