#%RAML 1.0 Trait
headers:
  client_id:
    required: true
  client_secret:
    required: true
queryParameters:
  Id: 
   required: false
   type: string
responses:
  200:
    body:
     application/json:
       example: !include Data_example.raml
      
    