db:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "![XZrap/sIacI=]"
 
smtp: 
  host: "smtp.gmail.com"
  port: "587"
  user: "![ta/07ujgWjQdnWI7j6MyzFI/u74hlgHM1aGXz5p2QCM=]"
  password: "![cmVm7dDvP5eOzf1IZJpdfA==]"