#%RAML 1.0
title: Account_sapi
types:
  DataType: !include Example/Account_dataType.raml
traits:
  getDetails: !include Example/Get_trait.raml
  postDetails : !include Example/Post_trait.raml
  updateDetails: !include Example/Update_trait.raml

/account:
  get:
    is: [getDetails]
  

  post:
    headers:
      client_id : 
       required: true
       type: string
      client_secret:
        required: true
        type: string
    body:
      application/json:
        example: !include Example/Data_example.raml

    is: [postDetails]
       
    
  patch:
    headers:
      client_id : 
       required: true
       type: string
      client_secret:
        required: true
        type: string
    body:
      application/json:
        example: !include Example/Data_example.raml
        
    is: [updateDetails]
    
          
  